

-------------Initiate Program---------------------



04-07-2023 23:54:32.116 | -------------Initiating Utah Real Estate API Call-----------------
04-07-2023 23:54:55.043 | BatchProcessing.py |Error = 'NoneType' object is not subscriptable | Batch Calculator document limit overwritten to 200 from input
04-07-2023 23:54:58.030 | Request for 8 Batches sent to server
04-07-2023 23:54:58.073 | TimeUpdater Thread Successfully Started
04-07-2023 23:54:58.074 | BatchFunc Thread Successfully Started
04-07-2023 23:54:58.075 | ValueChecker Thread Successfully Started
04-07-2023 23:55:06.807 | BatchProgressGUI.py | Error = 'NoneType' object has no attribute 'tk' | Timer string attribute error, this is okay if the display looks good, this exception omits fatal crashes due to an aesthetic error
04-07-2023 23:55:08.019 | Dataframe retrieved with 1445 rows and 45 columns in 00:00:13
04-07-2023 23:55:09.587 | ure API request Completed | File Appended and Saved to C:\Users\Kydoimos97\Documents\GardnerUtilData\04072023\ure_04072023_235508.csv | Exit Code 0
04-07-2023 23:55:09.587 | Appending Statistics | Method: ure | Appending file rows: 1445, Total Rows: 2890, Duplicates Dropped 1445
04-07-2023 23:55:09.587 | -------------Closing Utah Real Estate API Call---------------------


04-07-2023 23:55:11.471 | -------------Initiating Construction Monitor API Call-----------------
04-07-2023 23:55:16.671 | Request for 1 Batches sent to server
04-07-2023 23:55:16.710 | TimeUpdater Thread Successfully Started
04-07-2023 23:55:16.710 | BatchFunc Thread Successfully Started
04-07-2023 23:55:16.711 | ValueChecker Thread Successfully Started
04-07-2023 23:55:19.276 | BatchProgressGUI.py | Error = 'NoneType' object has no attribute 'tk' | Timer string attribute error, this is okay if the display looks good, this exception omits fatal crashes due to an aesthetic error
04-07-2023 23:55:19.824 | Dataframe retrieved with 345 rows and 144 columns in 00:00:04
04-07-2023 23:55:20.461 | cm API request Completed | File Saved to C:\Users\Kydoimos97\Documents\GardnerUtilData\04072023\cm_04072023_235519.csv | Exit Code 0
04-07-2023 23:55:20.461 | -------------Closing Construction Monitor API Call---------------------


04-07-2023 23:55:20.933 | -------------Initiating Construction Monitor API Call-----------------
04-07-2023 23:55:32.069 | Request for 2 Batches sent to server
04-07-2023 23:55:32.107 | TimeUpdater Thread Successfully Started
04-07-2023 23:55:32.107 | BatchFunc Thread Successfully Started
04-07-2023 23:55:32.108 | ValueChecker Thread Successfully Started
04-07-2023 23:55:41.007 | BatchProgressGUI.py | Error = 'NoneType' object has no attribute 'tk' | Timer string attribute error, this is okay if the display looks good, this exception omits fatal crashes due to an aesthetic error
04-07-2023 23:55:41.695 | Dataframe retrieved with 1370 rows and 144 columns in 00:00:10
04-07-2023 23:55:42.582 | cm API request Completed | File Appended and Saved to C:\Users\Kydoimos97\Documents\GardnerUtilData\04072023\cm_04072023_235541.csv | Exit Code 0
04-07-2023 23:55:42.582 | Appending Statistics | Method: cm | Appending file rows: 345, Total Rows: 1715, Duplicates Dropped 345
04-07-2023 23:55:42.582 | -------------Closing Construction Monitor API Call---------------------


04-07-2023 23:55:43.829 | -------------Initiating Authorization Utility-----------------
04-07-2023 23:55:45.445 | Authutil.py |Error = argument 1: <class 'TypeError'>: Don't know how to convert parameter 1 | Error when setting the key file as hidden. This is a common problem due to permission errors. Continuing...
04-07-2023 23:55:45.445 | -------------Closing Census API Call---------------------


04-07-2023 23:55:46.556 | -------------Data Folder Opened-----------------

04-07-2023 23:55:49.458 | -------------Initiating Construction Monitor API Call-----------------
Exception in thread Thread-13 (__getCount):
Traceback (most recent call last):
  File "C:\Users\Kydoimos97\.conda\envs\Core\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Kydoimos97\.conda\envs\Core\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\Kydoimos97\API_Calls\Sources\ConstructionMonitor\Core.py", line 401, in __getCount
    self.__record_val = __count_resp["hits"]["total"]["value"]
KeyError: 'hits'
04-07-2023 23:55:51.540 | Resource Response: 994
04-07-2023 23:55:51.540 | Status Code = 994 | Submission Error, server returned no documents
04-07-2023 23:55:56.569 | Resource Response: 1001
Traceback (most recent call last):
  File "D:\Users\Kydoimos97\API_Calls\Sources\ConstructionMonitor\Core.py", line 251, in __init__
    self.mainFunc()
  File "D:\Users\Kydoimos97\API_Calls\Sources\ConstructionMonitor\Core.py", line 314, in mainFunc
    RESTError(994)
  File "D:\Users\Kydoimos97\API_Calls\Functions\ErrorFunc\RESTError.py", line 135, in RESTError
    raise ValueError(textString)
ValueError: 04-07-2023 23:55:51.540 | Status Code = 994 | Submission Error, server returned no documents

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Kydoimos97\API_Calls\_main_.py", line 17, in <module>
    initializer()
  File "D:\Users\Kydoimos97\API_Calls\Initializer.py", line 57, in __init__
    self.__ShowGui(self.__CreateFrame(), "Data Tool")
  File "D:\Users\Kydoimos97\API_Calls\Initializer.py", line 90, in __ShowGui
    ConstructionMonitorMain(ConstructionMonitorInit())
  File "D:\Users\Kydoimos97\API_Calls\Sources\ConstructionMonitor\Core.py", line 273, in __init__
    RESTError(1001)
  File "D:\Users\Kydoimos97\API_Calls\Functions\ErrorFunc\RESTError.py", line 144, in RESTError
    raise SystemError(textString)
SystemError: 04-07-2023 23:55:56.569 | Status Code = 1001 | Main Function Error Break
